name: TourGuide Continuous Integration

on:
  push:
    branches:
      - "master"
      - "github-actions"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download sources
        uses: actions/checkout@v4

      - name: Install gpsUtil JAR
        run: mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar

      - name: Install tripPricer JAR
        run:  mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

      - name: Install rewardCentral JAR
        run: mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

  compile:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: compile with Maven
        run: mvn clean compile
        working-directory: TourGuide

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Run tests
        run: mvn test
        working-directory: TourGuide

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Package the app
        run: mvn -Dmaven.test.skip=true package --file TourGuide/pom.xml