name: TourGuide Continuous Integration

on:
  push:
    branches:
      - "master"
      - "github-actions"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean compile
        working-directory: TourGuide

      - name: Run tests
        run: mvn test
        working-directory: TourGuide

      - name: Package the app
        run: mvn package --file pom.xml
        working-directory: TourGuide

      - name: Deploy the app
        if: github.ref == 'refs/heads/master'
        run: mvn deploy
        working-directory: TourGuide